using UnityEngine;
// This is a auto generated code by chatGPT-4 deep model. so
//If this is a lisenced code, please notify me immediately.



#pragma warning disable IDE0130 // Namespace does not match folder structure
namespace SingletonPattern
#pragma warning restore IDE0130 // Namespace does not match folder structure
{
    /// <summary>
    /// Generic singleton definition for MonoBehaviour classes.
    /// Usage: Inherit from SingletonDefination&lt;YourClassName&gt;
    /// </summary>
    /// <typeparam name="T">Type of the singleton class.</typeparam>
    public class SceneLevelSingleTon<T> : MonoBehaviour where T : MonoBehaviour
    {
        private static T instance;
        private static readonly object lockObj = new();

        public static T Instance
        {
            get
            {
                if (instance == null)
                {
                    lock (lockObj)
                    {
                        if (instance == null)
                        {
                            instance = FindFirstObjectByType<T>();
                            if (instance == null)
                            {
                                GameObject singletonObject = new(typeof(T).Name + "AutoGenerated");
                                instance = singletonObject.AddComponent<T>();
                                DontDestroyOnLoad(singletonObject);
                            }
                        }
                    }
                }
                return instance;
            }
        }

        protected virtual void Awake()
        {
            if (instance == null)
            {
                instance = this as T;
            }
            else if (instance != this)
            {
                Destroy(gameObject);
            }
        }
    }
}