using UnityEngine;
using System.Collections.Generic;
using System;

namespace ServiceLocatorPattern
{

    public class ServiceLocator<T> : MonoBehaviour where T : MonoBehaviour
    {
        private static T instance;
        private static readonly object lockObj = new();
        protected readonly Dictionary<Type, object> services = new();
        protected bool isPersistent = false;

        public static T Instance
        {
            get
            {
                if (instance == null)
                {
                    lock (lockObj)
                    {
                        if (instance == null)
                        {
                            instance = FindFirstObjectByType<T>();
                            if (instance == null)
                            {
                                GameObject singletonObject = new(typeof(T).Name + "_AutoGenerated");
                                instance = singletonObject.AddComponent<T>();
                            }
                        }
                    }
                }
                return instance;
            }
        }

        protected virtual void Awake()
        {
            if (instance == null)
            {
                instance = this as T;
                if (this.isPersistent)
                {
                    transform.SetParent(null);
                    DontDestroyOnLoad(this.gameObject);
                }
            }
            else if (instance != this)
            {
                Destroy(gameObject);
            }
        }


        public void RegisterService<TService>(TService service) where TService : MonoBehaviour
        {
            if (service == null)
            {
                Debug.LogError("Cannot register a null service.");
                return;
            }
            var type = typeof(TService);
            if (!this.services.ContainsKey(type))
            {
                this.services[type] = service;
            }
            else
            {
                Logger.Warn($"Service of type {type} is already registered.");
            }
        }

        public void RegisterService<TService>() where TService : MonoBehaviour
        {

            var type = typeof(TService);
            if (!this.services.ContainsKey(type))
            {
                var service = CheckSceneOrCreate<TService>();
                this.services[type] = service;
            }
            else
            {
                Logger.Warn($"Service of type {type} is already registered.");
            }

        }

        private bool GetService<TService>(out TService service) where TService : MonoBehaviour
        {
            var type = typeof(TService);
            if (this.services.TryGetValue(type, out var foundService))
            {
                service = (TService)foundService;
                return true;
            }
            service = null;
            return false;
        }

        public TService GetORCreateDefault<TService>() where TService : MonoBehaviour
        {
            if (GetService<TService>(out var service))
            {
                return service;
            }
            var newService = CheckSceneOrCreate<TService>();
            RegisterService(newService);
            return newService;
        }

        protected TService CheckSceneOrCreate<TService>() where TService : MonoBehaviour
        {
            TService service = FindFirstObjectByType<TService>();
            if (service != null)
            {
                return service;
            }
            return new GameObject($"{typeof(TService).Name}_AutoGenerated").AddComponent<TService>();
        }

        public void UnregisterService<TService>() where TService : MonoBehaviour
        {
            var type = typeof(TService);
            if (this.services.ContainsKey(type))
            {
                this.services.Remove(type);
            }
            else
            {
                Debug.LogWarning($"Service of type {type} is not registered.");
            }
        }

        public bool HasService<TService>() where TService : MonoBehaviour
        {
            return services.ContainsKey(typeof(TService));
        }
        protected virtual void OnDestroy()
        {
            foreach (var service in services.Values)
            {
                if (service is MonoBehaviour mb)
                {
                    Destroy(mb.gameObject);
                }
            }
            services.Clear();
        }

    }
}