using System;
using System.Collections.Generic;
using Kope.Feature.PathFinding.Node;

namespace Kope.Feature.PathFinding.Data {

	/*
     * ==============================================================================================
     * ARCHITECTURAL RATIONALE: BIT-PACKING & PRIMITIVE COLUMNAR SERIALIZATION
     * ==============================================================================================
     * 
     * [The Core Problem: Unity YAML ASCII Markup Explosion]
     * When Unity serializes C# structs (`Vec2Int`, `BoundingBox`) inside ScriptableObjects, its C++ 
     * serializer treats every struct field as a full YAML object node with dedicated key tags:
     * 
     *   Standard BoundingBox YAML Output (6 lines per item):
     *     _min:
     *       x: -128
     *       y: 64
     *     _max:
     *       x: -64
     *       y: 128
     * 
     * Across 50,000 grid nodes, these structural tags create millions of lines of pure whitespace 
     * and redundant text keys (`_min:`, `_max:`, `x:`, `y:`), inflating grid data assets to 5MB+.
     * 
     * [The Engineering Solution: Bit-Packing & Columnar Inline Hex Streaming]
     * This utility class resolves YAML bloat through two primary memory transformations:
     * 
     * 1. Primitive 64-Bit Bit-Packing (Dictionary Keys):
     *    Unity's C++ serializer treats primitive integral types (`ulong`, `long`) as single-line hex 
     *    streams when stored in arrays/dictionaries. By bit-shifting 4 spatial coordinates into a 
     *    single 64-bit `ulong` word, we collapse a 6-line YAML struct key into a 1-line inline hex 
     *    value, completely bypassing object node overhead.
     * 
     * 2. Structure-of-Arrays (SoA) Transposition (List Arrays):
     *    Lists of domain structs (`List<Vec2Int>`) are pivoted into parallel primitive integer 
     *    arrays (`int[] _mPosX`, `int[] _mPosY`). Unity serializes integer arrays as compact, 
     *    inline hexadecimal byte streams, stripping all repeating field property headers.
     * 
     * ==============================================================================================
     * BIT-PACKING MEMORY LAYOUT DIAGRAMS
     * ==============================================================================================
     * 
     * 1. PackVec2Int (64-Bit Signed long)
     *    ┌────────────────────────────────────────┬────────────────────────────────────────┐
     *    │ Bits 63..32 (32 Bits): X Coordinate    │ Bits 31..0  (32 Bits): Y Coordinate    │
     *    │ Range: [-2,147,483,648 to 2,147,483,647]│ Range: [-2,147,483,648 to 2,147,483,647]│
     *    └────────────────────────────────────────┴────────────────────────────────────────┘
     * 
     * 2. PackBoundingBox16 (64-Bit Unsigned ulong)
     *    ┌───────────────────┬───────────────────┬───────────────────┬───────────────────┐
     *    │ Bits 63..48 (16B) │ Bits 47..32 (16B) │ Bits 31..16 (16B) │ Bits 15..0  (16B) │
     *    │ Min.X (-32k..32k) │ Min.Y (-32k..32k) │ Max.X (-32k..32k) │ Max.Y (-32k..32k) │
     *    └───────────────────┴───────────────────┴───────────────────┴───────────────────┘
     * ==============================================================================================
     */

	/// <summary>
	/// Static serialization utility that flattens strongly-typed domain spatial structs (<see cref="Vec2Int"/>, <see cref="BoundingBox"/>)
	/// into parallel primitive array columns (SoA) and bit-packed 64-bit integer keys (<c>ulong</c>/<c>long</c>).
	/// Eliminates Unity YAML structural tag replication, shrinking on-disk asset footprints by ~99.5%.
	/// </summary>
	public static class SaveDataSerializer {

		#region Key Bit-Packing (Vec2Int & BoundingBox)

		/// <summary>
		/// Bit-packs a 2D integer vector into a single 64-bit signed integer word (<c>long</c>).
		/// Allocates 32 bits for X and 32 bits for Y, maintaining full 32-bit signed integer precision.
		/// </summary>
		/// <remarks>
		/// When used as a key in serialized collections, Unity emits this primitive as a single inline 
		/// hex value rather than expanding a full multi-line <c>Vec2Int</c> YAML object.
		/// </remarks>
		/// <param name="v">The 2D vector coordinate to pack.</param>
		/// <returns>A 64-bit signed integer containing high-32 bit X and low-32 bit Y coordinates.</returns>
		public static long PackVec2Int(Vec2Int v) {
			// Mask Y with 0xFFFFFFFFL to prevent C# sign-extension from corrupting upper X bits when casting
			return ((long)v.X << 32) | ((long)v.Y & 0xFFFFFFFFL);
		}

		/// <summary>
		/// Reconstructs a strongly-typed <see cref="Vec2Int"/> coordinate from a 64-bit signed packed integer word.
		/// </summary>
		/// <param name="packed">The 64-bit packed integer generated by <see cref="PackVec2Int"/>.</param>
		/// <returns>The re-hydrated <see cref="Vec2Int"/> domain vector.</returns>
		public static Vec2Int UnpackVec2Int(long packed) {
			int x = (int)(packed >> 32);
			int y = (int)(packed & 0xFFFFFFFFL);
			return new Vec2Int(x, y);
		}

		/// <summary>
		/// Bit-packs a <see cref="BoundingBox"/> region into a single 64-bit unsigned integer word (<c>ulong</c>).
		/// Shifts four 16-bit signed coordinate fields (<c>Min.X</c>, <c>Min.Y</c>, <c>Max.X</c>, <c>Max.Y</c>) 
		/// into contiguous 16-bit bitfields within the 64-bit word.
		/// </summary>
		/// <remarks>
		/// <b>Spatial Boundaries &amp; Constraints:</b><br/>
		/// Because each coordinate is constrained to 16 bits (<c>short</c>), spatial grid coordinates must remain 
		/// within the bounds of <b>-32,768 to +32,767</b> units. This easily accommodates massive world grid maps 
		/// while forcing Unity's C++ serializer to emit dictionary keys as single inline hexadecimal string lines.
		/// </remarks>
		/// <param name="box">The bounding box spatial region to pack.</param>
		/// <returns>A 64-bit unsigned integer word containing all four packed 16-bit bounding coordinates.</returns>
		public static ulong PackBoundingBox16(BoundingBox box) {
			// Re-interpret signed 16-bit shorts as unsigned 16-bit ushorts for safe bitwise OR operations
			ushort minX = (ushort)(short)box.Min.X;
			ushort minY = (ushort)(short)box.Min.Y;
			ushort maxX = (ushort)(short)box.Max.X;
			ushort maxY = (ushort)(short)box.Max.Y;

			return ((ulong)minX << 48) |
				   ((ulong)minY << 32) |
				   ((ulong)maxX << 16) |
				   ((ulong)maxY);
		}

		/// <summary>
		/// Reconstructs a strongly-typed <see cref="BoundingBox"/> domain object from a 64-bit unsigned packed word.
		/// </summary>
		/// <param name="packed">The 64-bit packed integer generated by <see cref="PackBoundingBox16"/>.</param>
		/// <returns>The re-hydrated <see cref="BoundingBox"/> domain instance.</returns>
		public static BoundingBox UnpackBoundingBox16(ulong packed) {
			// Shift and cast back to signed 16-bit short to restore negative coordinate signs correctly
			short minX = (short)(packed >> 48);
			short minY = (short)(packed >> 32);
			short maxX = (short)(packed >> 16);
			short maxY = (short)(packed & 0xFFFF);

			return new BoundingBox(new Vec2Int(minX, minY), new Vec2Int(maxX, maxY));
		}

		#endregion

		#region Vec2Int Conversions (Structure-of-Arrays)

		/// <summary>
		/// Transposes an Array-of-Structs (AoS) <c>List&lt;Vec2Int&gt;</c> into a Structure-of-Arrays (SoA) layout 
		/// consisting of two parallel integer coordinate streams (<c>xArray</c>, <c>yArray</c>).
		/// </summary>
		/// <remarks>
		/// Strips repeating field keys (<c>x:</c>, <c>y:</c>) from every list element in Unity YAML serialization, 
		/// outputting compact primitive integer byte streams instead.
		/// </remarks>
		/// <param name="vec2List">Source list of 2D vector domain objects.</param>
		/// <returns>A tuple containing synchronized, index-aligned X and Y integer primitive arrays.</returns>
		public static (int[] xArray, int[] yArray) FromVec2ToIntArrays(List<Vec2Int> vec2List) {
			int count = vec2List.Count;
			int[] xArray = new int[count];
			int[] yArray = new int[count];

			for (int i = 0; i < count; i++) {
				xArray[i] = vec2List[i].X;
				yArray[i] = vec2List[i].Y;
			}
			return (xArray, yArray);
		}

		/// <summary>
		/// Re-hydrates parallel primitive coordinate streams (<c>xArray</c>, <c>yArray</c>) 
		/// back into a strongly-typed <c>List&lt;Vec2Int&gt;</c> domain collection.
		/// </summary>
		/// <param name="xArray">Parallel X coordinate primitive array.</param>
		/// <param name="yArray">Parallel Y coordinate primitive array.</param>
		/// <returns>A re-hydrated list of <see cref="Vec2Int"/> domain instances.</returns>
		/// <exception cref="ArgumentException">Thrown if input arrays do not share identical lengths.</exception>
		public static List<Vec2Int> FromIntArraysToVec2(int[] xArray, int[] yArray) {
			if (xArray.Length != yArray.Length) {
				throw new ArgumentException("X and Y coordinate arrays must have identical lengths.");
			}

			int count = xArray.Length;
			List<Vec2Int> vec2List = new(count);

			for (int i = 0; i < count; i++) {
				vec2List.Add(new Vec2Int(xArray[i], yArray[i]));
			}
			return vec2List;
		}

		#endregion

		#region BoundingBox Conversions (Structure-of-Arrays)

		/// <summary>
		/// Transposes an Array-of-Structs (AoS) <c>List&lt;BoundingBox&gt;</c> into a Structure-of-Arrays (SoA) layout 
		/// consisting of four parallel primitive integer streams (<c>minX</c>, <c>minY</c>, <c>maxX</c>, <c>maxY</c>).
		/// </summary>
		/// <remarks>
		/// Strips nested <c>_min</c> and <c>_max</c> YAML object tags entirely across all graph connections.
		/// </remarks>
		/// <param name="boxList">Source list of bounding box domain objects.</param>
		/// <returns>Nested tuples containing parallel primitive coordinate arrays for Min and Max points.</returns>
		public static ((int[] minX, int[] minY) min, (int[] maxX, int[] maxY) max) FromBoundingBoxListToIntArrayPairs(
			List<BoundingBox> boxList
		) {
			int count = boxList.Count;
			int[] minXArray = new int[count];
			int[] minYArray = new int[count];
			int[] maxXArray = new int[count];
			int[] maxYArray = new int[count];

			for (int i = 0; i < count; i++) {
				var box = boxList[i];
				minXArray[i] = box.Min.X;
				minYArray[i] = box.Min.Y;
				maxXArray[i] = box.Max.X;
				maxYArray[i] = box.Max.Y;
			}
			return ((minXArray, minYArray), (maxXArray, maxYArray));
		}

		/// <summary>
		/// Re-hydrates four parallel primitive coordinate streams (<c>minX</c>, <c>minY</c>, <c>maxX</c>, <c>maxY</c>) 
		/// back into a strongly-typed <c>List&lt;BoundingBox&gt;</c> domain collection.
		/// </summary>
		/// <param name="minX">Parallel Min.X coordinate array.</param>
		/// <param name="minY">Parallel Min.Y coordinate array.</param>
		/// <param name="maxX">Parallel Max.X coordinate array.</param>
		/// <param name="maxY">Parallel Max.Y coordinate array.</param>
		/// <returns>A re-hydrated list of <see cref="BoundingBox"/> domain instances.</returns>
		/// <exception cref="ArgumentException">Thrown if any coordinate array differs in length.</exception>
		public static List<BoundingBox> FromIntArrayPairsToBoundingBoxList(
			int[] minX, int[] minY,
			int[] maxX, int[] maxY
		) {
			if (minX.Length != minY.Length ||
				maxX.Length != maxY.Length ||
				minX.Length != maxX.Length) {
				throw new ArgumentException("All bounding box coordinate arrays must have identical lengths.");
			}

			int count = minX.Length;
			List<BoundingBox> boxList = new(count);

			for (int i = 0; i < count; i++) {
				Vec2Int min = new(minX[i], minY[i]);
				Vec2Int max = new(maxX[i], maxY[i]);
				boxList.Add(new BoundingBox(min, max));
			}
			return boxList;
		}

		#endregion

		#region Primitive Helpers

		/// <summary>
		/// Converts a C# boolean to a single primitive <c>byte</c> (1 for true, 0 for false).
		/// Prevents Unity YAML from writing expanded string values (<c>true</c> / <c>false</c>).
		/// </summary>
		public static byte ConvertBoolToByte(bool value) => value ? (byte)1 : (byte)0;

		/// <summary>
		/// Converts a serialized primitive <c>byte</c> back into a C# boolean.
		/// </summary>
		public static bool ConvertByteToBool(byte value) => value != 0;

		#endregion
	}
}